### PR TITLE
fix broken links to setup for dev/prod

### PR DESCRIPTION
**Pull request by whit537**
Looks like the wiki pages got moved around.

### CODE REVIEW

**Comment by gdpelican** [comment]
Ah thank you so much @whit537; this has been bugging me.

**Comment by gdpelican** [comment]
FYI we'll be going through the tech manual over the next 2 weeks and giving it a bunch of love. Watch this space!

**Comment by whit537** [comment]
Huzzah! :-)

**Comment by robguthrie** [comment]
Thank you so much for your help, Chad! I really appreciate it.

**Pull request merged**
